# -*- coding: utf-8 -*-
"""00 quarentena dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mIgvXneMEn3XfKBvZafXC0PqBHDcC9re
"""

import pandas as pd
import numpy as np

avaliacoes = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula0/ml-latest-small/ratings.csv')
filmes = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula0/ml-latest-small/movies.csv')

#avaliacoes.head()

avaliacoes.shape
len(avaliacoes['nota'])

avaliacoes.columns = ['UsuarioId', 'filmeId', 'nota', 'momento']
filmes.columns = ['filmeId', 'titulo', 'generos']

#avaliacoes.head()

notas_filme_1 = avaliacoes.query('filmeId == 1')
notas_filme_1['nota'].count()

avaliacoes.describe()

avaliacoes.head()

avaliacoes['nota']

notas_filme_1.head()

notas_medias_por_filme = avaliacoes.groupby('filmeId')['nota'].mean()
print(notas_medias_por_filme)

filmes_com_media = filmes.join(notas_medias_por_filme, on ='filmeId')

filmes_com_media.sort_values('nota', ascending=False).head(15)

filmes_com_media.sort_values('nota', ascending=False)

avaliacoes.query('filmeId == 1')['nota'].plot(kind='hist')

avaliacoes.query('filmeId == 2')['nota'].plot(kind='hist')

avaliacoes.query('filmeId == 102084')['nota'].plot(kind='hist')

# Desafio 1

filmes_sem_avaliacao = filmes_com_media.query('nota != nota')['titulo']

print('Quantidade de filmes sem avaliacao ', len(filmes_sem_avaliacao))
print('Filmes sem avaliacao: \n', filmes_sem_avaliacao)

# Desafio 2

filmes_com_media.columns = ['filmeId', 'titulo', 'generos', 'nota media']
filmes_com_media.head()

# Desafio 3

num_avaliacoes = avaliacoes.groupby('filmeId')['nota'].count()

filmes_com_num_de_avaliacoes = filmes_com_media.join(num_avaliacoes, on ='filmeId')
filmes_com_num_de_avaliacoes.columns = ['filmeId', 'titulo', 'generos', 'nota media', 'numero de votacoes']

filmes_com_num_de_avaliacoes.head()

# Desafio 4

filmes_com_media_arredondada = filmes_com_num_de_avaliacoes.round({'nota media': 2})
filmes_com_media_arredondada.head()

# Desafios 5 e 6
# Achei melhor mesclar os dois desafios em um só :)

lista_geral_generos = filmes['generos'].values.tolist()
dicionario_generos = {}

for conjunto_generos_index in range(len(lista_geral_generos)):
  lista_temporaria = lista_geral_generos[conjunto_generos_index].split('|')

  for genero in lista_temporaria:
    if genero not in dicionario_generos:
      dicionario_generos[genero] = 1
    else:
      dicionario_generos[genero] += 1

for genero in dicionario_generos:
  if dicionario_generos[genero] == 1:
    print('O genero {} aparece somente uma vez.'.format(genero))

print(dicionario_generos)

# Desafio 7

import matplotlib.pylab as plt

fig = plt.figure(figsize=(30,10))

plt.bar(range(len(dicionario_generos)), list(dicionario_generos.values()), align='center')
plt.xticks(range(len(dicionario_generos)), list(dicionario_generos.keys()))

plt.show()

