# -*- coding: utf-8 -*-
"""01 quarentena dados desafios dia 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17XeicCqz9q-aMbkIVl6mjdURXRj-u5eW
"""

import pandas as pd
import numpy as np
import matplotlib.pylab as plt

avaliacoes = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula0/ml-latest-small/ratings.csv')
filmes = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula0/ml-latest-small/movies.csv')

avaliacoes.columns = ['UsuarioId', 'filmeId', 'nota', 'momento']
filmes.columns = ['filmeId', 'titulo', 'generos']

notas_medias_por_filme = avaliacoes.groupby('filmeId')['nota'].mean()
filmes_com_media = filmes.join(notas_medias_por_filme, on ='filmeId')

# Desafio 1
filmes_sem_avaliacao = filmes_com_media.query('nota != nota')['titulo']

print('Quantidade de filmes sem avaliacao ', len(filmes_sem_avaliacao))
print('Filmes sem avaliacao: \n', filmes_sem_avaliacao)

# Desafio 2
filmes_com_media.columns = ['filmeId', 'titulo', 'generos', 'nota media']
filmes_com_media.head()

# Desafio 3
num_avaliacoes = avaliacoes.groupby('filmeId')['nota'].count()
filmes_com_num_de_avaliacoes = filmes_com_media.join(num_avaliacoes, on ='filmeId')
filmes_com_num_de_avaliacoes.columns = ['filmeId', 'titulo', 'generos', 'nota media', 'numero de votacoes']
filmes_com_num_de_avaliacoes.head()

# Desafio 4
filmes_com_media_arredondada = filmes_com_num_de_avaliacoes.round({'nota media': 2})
filmes_com_media_arredondada.head()

# Desafios 5 e 6
# Achei melhor mesclar os dois desafios em um só :)
lista_geral_generos = filmes['generos'].values.tolist()
dicionario_generos = {}

for conjunto_generos_index in range(len(lista_geral_generos)):
  lista_temporaria = lista_geral_generos[conjunto_generos_index].split('|')

  for genero in lista_temporaria:
    if genero not in dicionario_generos:
      dicionario_generos[genero] = 1
    else:
      dicionario_generos[genero] += 1

for genero in dicionario_generos:
  if dicionario_generos[genero] == 1:
    print('O genero {} aparece somente uma vez.'.format(genero))

print(dicionario_generos)

# Desafio 7
fig = plt.figure(figsize=(30,10))
plt.bar(range(len(dicionario_generos)), list(dicionario_generos.values()), align='center')
plt.xticks(range(len(dicionario_generos)), list(dicionario_generos.keys()))
plt.xlabel('Genero')
plt.ylabel('Numero de aparicoes')
plt.show()