# -*- coding: utf-8 -*-
"""02 quarentena dados desafios dia 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DWt4CRvpDsRnBdbClwgJqlH_Xa66e73j
"""

import pandas as pd
import numpy as np

avaliacoes = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula0/ml-latest-small/ratings.csv')
filmes = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula0/ml-latest-small/movies.csv')

avaliacoes.columns = ['UsuarioId', 'filmeId', 'nota', 'momento']
filmes.columns = ['filmeId', 'titulo', 'generos']

notas_medias_por_filme = avaliacoes.groupby('filmeId')['nota'].mean()
filmes_com_media = filmes.join(notas_medias_por_filme, on ='filmeId')

def plot_filme(n):
  notas_do_filme = avaliacoes.query(f"filmeId=={n}")["nota"]
  notas_do_filme.plot(kind='hist')
  plt.show()
  print('\n')
  notas_do_filme.plot.box()
  plt.show()
  return notas_do_filme.describe()

# Desafio 1
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('whitegrid')
filmes_por_genero = filmes['generos'].str.get_dummies('|').sum().sort_values(ascending=False)
plt.figure(figsize=(16,8))

chart = sns.barplot(
    x=filmes_por_genero.index,
    y=filmes_por_genero.values,
    palette=sns.color_palette("BuGn_r", n_colors=len(filmes_por_genero) + 4)
    )

chart.set_xticklabels(chart.get_xticklabels(), rotation=45)
chart

# Desafio 2
plot_filme(1)
plot_filme(2)
plot_filme(3)

# Desafio 3
num_avaliacoes = avaliacoes.groupby('filmeId')['nota'].count()

filmes_com_num_de_avaliacoes = filmes_com_media.join(num_avaliacoes, on ='filmeId')
filmes_com_num_de_avaliacoes.columns = ['filmeId', 'titulo', 'generos', 'nota media', 'numero de votacoes']

lista_id = filmes_com_num_de_avaliacoes.sort_values("numero de votacoes", ascending=False).head(10)['filmeId'].to_list()

sns.boxplot(
    data = avaliacoes.query("filmeId in {}".format(lista_id)), 
    x ="filmeId", 
    y="nota"
    )

lista_id_2 = [1,2,919,46578]

lista_nomes = filmes.query("filmeId in {}".format(lista_id_2))['titulo'].to_list()
lista_nomes

sns.boxplot(
    data=avaliacoes.query("filmeId in {}".format(lista_id_2)), 
    x="filmeId", 
    y="nota"
    )

plt.show()

set_id = set(avaliacoes.query("filmeId in [1,2,919,46578]")['filmeId'].to_list())
list(set_id)