# -*- coding: utf-8 -*-
"""03 quarentena dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R5234bc0xqUBcOApErZ8q75hdJ-kpRWa
"""

import pandas as pd
import numpy as np
import seaborn as sns

imdb = pd.read_csv("https://gist.githubusercontent.com/guilhermesilveira/24e271e68afe8fd257911217b88b2e07/raw/e70287fb1dcaad4215c3f3c9deda644058a616bc/movie_metadata.csv")
imdb.head()

imdb['color'].unique()

imdb['color'].value_counts()

imdb['color'].value_counts(normalize=True)

imdb['director_name'].value_counts()

imdb['director_name']

imdb['director_name'].value_counts().tail(40)

imdb['num_critic_for_reviews']

imdb['num_critic_for_reviews'].describe()

imdb['num_critic_for_reviews'].plot(
    kind='hist'
)

imdb['gross'].hist()

import seaborn as sns

sns.distplot(imdb['gross'])

imdb.sort_values('gross', ascending=False).head()

imdb.sort_values('gross', ascending=False).sample(10)

color_or_bw = imdb.query("color in ['Color', ' Black and White']")
len(color_or_bw)

color_or_bw['color_0_ou_1'] = (color_or_bw['color']=='Color')*1
color_or_bw.head()

color_or_bw['color_0_ou_1'].value_counts()

sns.scatterplot(
    data=color_or_bw,
    x='color_0_ou_1',
    y='gross'
    )

color_or_bw.groupby('color').mean()['imdb_score']

color_or_bw.groupby('color').median()['imdb_score']

budget_gross = imdb[['budget', 'gross']].dropna().query('budget>0 | gross>0')

sns.scatterplot(
    data=budget_gross,
    x='budget',
    y='gross'
    )

imdb.sort_values('budget', ascending=False).head()

imdb['country'].unique()

imdb = imdb.drop_duplicates()

imdb_usa = imdb.query("country == 'USA'")
imdb_usa.sort_values('budget', ascending=False).head()

budget_gross = imdb_usa[['budget', 'gross']].dropna().query('budget>0 | gross>0')

sns.scatterplot(
    data=budget_gross,
    x='budget',
    y='gross'
    )

imdb_usa['lucro'] = imdb_usa['gross']-imdb_usa['budget']
budget_gross = imdb_usa.query('budget>0 | gross>0')[['budget', 'lucro']].dropna()

sns.scatterplot(
    data=budget_gross,
    x='budget',
    y='lucro'
    )

budget_gross = imdb_usa.query('budget>0 | gross>0')[['title_year', 'lucro']].dropna()

sns.scatterplot(
    data=budget_gross,
    x='title_year',
    y='lucro'
    )

imdb_usa['director_name'].value_counts()

filmes_por_diretor = imdb_usa['director_name'].value_counts()
filmes_por_diretor.head()

gross_director = imdb_usa[['director_name', 'gross']].set_index('director_name').join(filmes_por_diretor, on='director_name')
gross_director.columns = ['orcamento', 'filmes_irmaos']
gross_director = gross_director.reset_index()
gross_director.head()

budget_gross = imdb_usa.query('budget>0 | gross>0')[['title_year', 'lucro']].dropna()

sns.scatterplot(
    data=gross_director,
    x='filmes_irmaos',
    y='orcamento'
)

